#
# Whenever version.php is changed, add the latest version
# to the Moodle Plugins directory at https://moodle.org/plugins
#
name: VERSION2 - Releasing in the Plugins directory

on:
  push:
    branches:
      - VERSION2
    paths:
      - 'version.php'

jobs:
  workflow_group_33_to_39_release:
    uses: catalyst/catalyst-moodle-workflows/.github/workflows/group-33-to-39-release.yml@main
    with:
      plugin_name: local_envbar
    secrets:
      moodle_org_token: ${{ secrets.MOODLE_ORG_TOKEN }}
